---
env:
  browser: true
extends:
  - standard
  - prettier
parserOptions:
  ecmaVersion: 2015
  sourceType: module
rules: {}
overrides:
  - files: './app/webpacker/packs/application.js'
    rules:
      no-unused-expressions: off
      no-unused-vars: off
